<div class="card text-center shadow">
    <div class="card-header">
        PERFIL PROFESIONAL
    </div>
    <div class="card-body">
        <h5 class="card-title">William Rojas Rojas - Ingeniero de Sistemas</h5>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque ipsum sunt, et eveniet aliquam, amet nam iste commodi a magnam consequatur esse eius perferendis sequi? Dolorem accusantium dolor dolore eos hic error unde nihil vitae pariatur, sapiente obcaecati fugit. Reprehenderit excepturi accusantium quidem ad incidunt id quibusdam quam nulla optio qui.
            Sunt cupiditate aperiam corporis quam eos quod ad repudiandae vero ipsa ex. Nihil eaque molestias sint, illum quaerat laborum ad officia laudantium voluptates vitae, voluptatem ducimus vero illo odio suscipit quod, magnam porro facere tenetur itaque blanditiis. Similique blanditiis laudantium, iusto eveniet quo, placeat temporibus natus magnam fugiat aspernatur in nam iste corporis omnis aliquam deleniti libero ab molestias dolores, cum itaque impedit labore laborum rem! Perspiciatis rem distinctio dicta nemo magnam amet tempora doloribus et libero numquam quia sed, molestias nam perferendis, nobis delectus. Provident illo molestiae cupiditate dignissimos quidem ipsum voluptas soluta excepturi minus dolorem voluptatibus adipisci perspiciatis unde, nostrum aut eveniet consequuntur dolore quaerat blanditiis quas error tempore explicabo nesciunt! Molestias repellendus consectetur accusamus. Ipsam pariatur quibusdam provident perspiciatis possimus aliquam reprehenderit! Minima debitis nihil assumenda rem sed incidunt placeat autem aperiam sint, quas quos expedita repellat est qui fugiat reprehenderit tenetur unde odit facere magnam sunt at. Molestias quam earum corporis asperiores debitis blanditiis doloremque voluptas esse! Maxime ipsam laudantium eum obcaecati nemo temporibus, labore veritatis iure aperiam neque consectetur doloribus consequuntur sed, suscipit esse exercitationem explicabo? Omnis commodi velit eius unde? Porro sapiente accusantium explicabo maxime dolorem. Rem architecto necessitatibus maxime vel aliquid error officiis dolores accusantium consequatur, debitis deserunt! Quibusdam excepturi hic distinctio architecto nisi culpa consequuntur modi. Nam placeat recusandae explicabo a! Sit in quasi voluptatum nemo exercitationem, nam assumenda doloribus maxime tempore saepe, tenetur aut itaque? Velit quos laudantium, voluptates quisquam rerum ex tenetur neque, in ipsam provident vel autem explicabo!</p>
    </div>
    <div class="card-footer text-muted">
        <a href="https://www.facebook.com/wiros2" target="_blank"><i class="fa-brands fa-facebook fa-2xl"></i></a>
        <a href="https://www.instagram.com/wiros2/" target="_blank"><i class="fa-brands fa-square-instagram fa-2xl" style="color: #f01976;"></i></a>
        <a href="mailto:wiros2@gmail.com"><i class="fa-solid fa-envelope fa-2xl"></i></a>
        <a href="https://wa.me/573182744252" target="_blank"><i class="fa-brands fa-whatsapp fa-2xl" style="color: #3eac7b;"></i></a>
    </div>
</div>